entrypoint: "gunicorn -b :$PORT app:app --timeout 500"
runtime: python
env: flex
service: marine-mammal-classifier
runtime_config:
  python_version: 3.9
instance_class: B1
manual_scaling:
  instances: 1
liveness_check:
  path: "/liveness_check"
